# -----------------------------------------------------------------------------
# models.py — Defines the shape of every request and response in the API.
#
# Pydantic models act as contracts between the frontend and the backend.
# They automatically validate incoming data and document what each endpoint
# expects and returns. If a required field is missing or has the wrong type,
# FastAPI returns a clear validation error automatically.
# -----------------------------------------------------------------------------

from pydantic import BaseModel, Field


# ── Request Models ────────────────────────────────────────────────────────────
# These describe what the frontend must send to each endpoint.

class QueryRequest(BaseModel):
    """Body for POST /query — a plain-English question from the user."""
    query: str = Field(..., min_length=1, description="The natural language question to answer")


class ExplainRequest(BaseModel):
    """Body for POST /explain — the original question plus the result rows to explain."""
    query:  str              = Field(..., description="The original question the user asked")
    result: list[dict]       = Field(..., description="The result rows returned by /query")


# ── Response Models ───────────────────────────────────────────────────────────
# These describe what the backend sends back to the frontend.

class QueryResponse(BaseModel):
    """
    Response from POST /query.

    On success: columns, rows, and metadata are populated; error is null.
    On failure: error is populated with a human-readable message.
    """
    # The actual data
    columns:        list[str]        = Field(default_factory=list, description="Column names in order")
    rows:           list[dict]       = Field(default_factory=list, description="Result rows as key-value pairs")
    row_count:      int              = Field(default=0,            description="Total number of rows returned")

    # Metadata used by the frontend to render the result
    chart_hint:     str | None       = Field(default=None,  description="Suggested chart type: 'line', 'bar', 'pie', or null")
    plan_available: bool             = Field(default=True,  description="False if plan data was requested but not found")
    temporal_mode:  str | None       = Field(default=None,  description="Detected time mode: 'YTD', 'MTD', or null")

    # The SQL that was generated — useful for debugging and transparency
    sql:            str | None       = Field(default=None,  description="The SQL query generated by the LLM")

    # Populated only when something goes wrong
    error:          str | None       = Field(default=None,  description="Error message if the query failed")


class ExplainResponse(BaseModel):
    """Response from POST /explain — a plain-English summary of the results."""
    narrative: str = Field(..., description="A 2-3 sentence plain-English explanation of the result")


class HealthResponse(BaseModel):
    """Response from GET /health — reports whether each system component is up."""
    status:        str  = Field(..., description="'ok' if all systems are healthy, 'degraded' otherwise")
    db_connected:  bool = Field(..., description="True if the DuckDB database file is accessible")
    llm_reachable: bool = Field(..., description="True if Ollama is running and the configured model is available")
