# -----------------------------------------------------------------------------
# validator.py — Checks that the SQL generated by the LLM is safe to run.
#
# Before we execute any SQL on the database, we run two checks:
#
#   1. SAFETY CHECK — Block any SQL that could modify or delete data.
#      We are a read-only analytics system. The LLM should never generate
#      DELETE, DROP, INSERT etc., but we enforce this as a hard guard.
#
#   2. SYNTAX CHECK — Ask DuckDB to parse the SQL without running it.
#      If the LLM produced malformed SQL (e.g. a missing closing bracket),
#      we catch that here and return a clear error instead of crashing.
# -----------------------------------------------------------------------------

import re
import duckdb

# SQL keywords that could modify or destroy data.
# Any SQL containing these words will be rejected immediately.
FORBIDDEN_KEYWORDS = {"drop", "delete", "insert", "update", "create", "alter", "truncate"}


def validate_sql(sql: str, conn: duckdb.DuckDBPyConnection) -> str | None:
    """
    Validates the SQL string for safety and syntax correctness.

    Returns None if the SQL is valid and safe to run.
    Returns an error message string if something is wrong.

    sql  — the SQL string generated by the LLM
    conn — an open DuckDB connection (used for the EXPLAIN syntax check)
    """

    # ── Safety Check ──────────────────────────────────────────────────────────
    # Tokenize the SQL into individual words and check against the forbidden list.
    # We use word boundaries (\b) to avoid false positives
    # (e.g. "created_at" should not be blocked just because it contains "create").
    sql_lower = sql.lower()
    for keyword in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{keyword}\b", sql_lower):
            return (
                f"Query blocked: SQL contains the forbidden keyword '{keyword.upper()}'. "
                f"Only SELECT queries are allowed."
            )

    # ── Syntax Check ─────────────────────────────────────────────────────────
    # DuckDB's EXPLAIN command parses the SQL without executing it.
    # If the SQL has a syntax error, EXPLAIN will raise an exception.
    try:
        conn.execute(f"EXPLAIN {sql}")
    except Exception as e:
        return f"SQL syntax error: {e}"

    # SQL passed both checks — it is safe to execute
    return None
